#!/bin/bash
key=$1
encryptkey=$2
algorithm=$3

if [[ $# -lt 3 ]]
then
	echo "Arguments not given. Usage: ./checkcert.sh PRIVKEY.key Encryptkey.key algorithm"
	echo "Algorithm：aes128|aes192|aes256|camellia128|camellia192|camellia256|des|des3|idea"
else
	decryptkey=$(openssl rsa "-$algorithm" -in "$key" -out "$encryptkey")
fi
